# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ARGEARSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ARGEARSample
	pod 'AFNetworking', '~> 3.0'
	pod 'SDWebImage', '~> 5.0'
  pod 'Realm', '~> 3.19.0'
  pod 'Toast', '~> 4.0.0'

end
